### ISSUE TITLE
error

### ISSUE THREAD

**Issue by qiurigao** [RC1844/Actions-Build-TWRP-For-Begonia#1]
[100% 183/183] out/soong/.bootstrap/bin/soong_build out/soong/build.ninja
FAILED: out/soong/build.ninja
out/soong/.bootstrap/bin/soong_build -t -l out/.module_paths/Android.bp.list -b out/soong -n out -d out/soong/build.ninja.d -globFile out/soong/.bootstrap/build-globs.ninja -o out/soong/build.ninja Android.bp
Killed
02:20:36 soong bootstrap failed with: exit status 1
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.

**Comment by RC1844** [comment]
Solve the problem yourself
